### ISSUE TITLE
Geocoding (eigener Standort) funktioniert nur noch auf Mobile

### ISSUE THREAD

**Issue by magdalena19** [magdalena19/lberg-map#103]
Komischerweise funktioniert bei mir unter Firefox und Chrome die Standorterkennung nicht mehr. Es passiert einfach nichts, wenn ich auf  den entsprechenden Button (Add Place Via Location) klicke. Auf meinem Smartphone funktioniert es wunderbar.

@haithembelhaj das ist vielleicht etwas, an das du dich setzen kannst, da es eigentlich eine reine JavaScript-Angelegenheit ist. Hier ist der Code: https://github.com/magdalena19/lberg-map/blob/master/app/assets/javascripts/map.js.erb#L131

**Comment by andneuma** [comment]
@kjoscha Problem confirmed, komisch... hast du das von einer anderen Internet-Verbindung mal geprüft? Sprich: ge-tethertes Internet vom Handy oder auf Arbeit mal geguckt?

**Comment by magdalena19** [comment]
nee glaub nicht. Man kann sich aber im JavaScript mal eine Fehlermeldung von dem API-Request ausgeben lassen...

**Comment by magdalena19** [comment]
komisch, auch über Tethering das selbe. Aufschlussreiche Fehlermeldung: "Unknown error acquiring position"

**Comment by magdalena19** [comment]
Gibt nun eine mehrsprachige Error-Message, dass das Feature vor allem auf mobilen Geräten verfügbar ist.
