### ISSUE TITLE
NiceEdit inserts <br>

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#112]
..which sucks big time!!

=> test e.g. via Create "empty" announcement

**Comment by magdalena19** [comment]
wo und wann genau wird ein `<br>` eingefügt??

**Comment by magdalena19** [comment]
ah i see. Dann über Javascript dafür sorgen, dass das nicht passiert oder in den jeweiligen Controllern checken und ggf. den Tag rausnehmen, oder?

**Comment by andneuma** [comment]
Nee, irgendwie nicht... `if(this.getContent()==""){this.setContent("<br />")}` ist das Problem und die ist noch im Master drin

**Comment by andneuma** [comment]
Done via #

**Comment by andneuma** [comment]
Solved by #120
