### ISSUE TITLE
Reviewing Bugs

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#122]
- [x] Translations of new POIs do not appear on reviewing index, proposal for **review controller**
```
def unreviewed_translations(place)
    place.translations.select { |t| !t.reviewed }
end
```
- [ ] Wenn POI geändert und vor dem confirm/reject zugehörige Translation geändert wird, wird eine zweite Version angelegt

- [x] `reviewed` wird im controller für descriptions nach confirmation nicht gesetzt weshalb es für descriptions nie eine gereviewte version geben kann

**Comment by magdalena19** [comment]
also, ich habe mich nun nochmal hiermit beschäftigt. Es war irgendwie totales durcheinander und ich habe nichts mehr durchblickt, daher habe ich es nun weitestgehend zurückgesetzt auf die Master-Version. Es werden bei einem neu hinzugefügten Ort also alle Descriptions mit confirmed. Letztere werden im entsprechenden place-review-View nun ausgegraut angezeigt.

**Comment by magdalena19** [comment]
Diesen Bug kann ich irgendwie nicht nachvollziehen:

>  Wenn POI geändert und vor dem confirm/reject zugehörige Translation geändert wird, wird eine zweite Version angelegt

**Comment by magdalena19** [comment]
Die anderen beiden "Bugs" haben sich erübrigt, wenn wir bei dem jetzigen System bleiben
