### ISSUE TITLE
Geocoding-Fehler

### ISSUE THREAD

**Issue by magdalena19** [magdalena19/lberg-map#128]
Wenn Punkt im Interface geocodet wird (über Locate-Me-Button), brauch die Adresse danach im Formular nicht mehr confirmed (nochmal durch den Geocoder gejagt) werden...

**Comment by magdalena19** [comment]
Gibt nun eine mehrsprachige Error-Message, dass das Feature vor allem auf mobilen Geräten verfügbar ist.

**Comment by magdalena19** [comment]
das machst du @andneuma , oder?

**Comment by andneuma** [comment]
ja, hab schon in nem branch ein bisschen was dazu gemacht

**Comment by andneuma** [comment]
Bearbeitet in #131
