### ISSUE TITLE
Accordion for place descriptions in slidepanel...

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#137]
...not working

**Comment by magdalena19** [comment]
goly shit, wie ist das denn kaputt gegangen?!

**Comment by magdalena19** [comment]
ok, konnte herausfinden, dass es in commit https://github.com/magdalena19/lberg-map/commit/c10e9a10199db648e2e87d21cc52c7eccfaa74b6 passiert ist.

**Comment by andneuma** [comment]
puh, also nicht meine Schuld :D

**Comment by magdalena19** [comment]
so easy und doch so lange gebraucht :/

**Comment by magdalena19** [comment]
https://github.com/magdalena19/lberg-map/commit/94690e74e5951eb045e9a07c3cdf94b6c5307749
