### ISSUE TITLE
Neue POIs für User doppelt angezeigt

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#146]
Wenn ich einen neuen Punkt anlege erscheint der zweimal. Ist weird, die Controller Tests laufen ja alle oO

**Comment by andneuma** [comment]
Failing feature test

```
scenario 'create valid place', :js do
    login
    visit '/places/new'
    fill_in_valid_place_information
    click_on('Create place')
    visit '/places'
    page.must_have_content('Any place')
    page.must_have_css('.glyphicon-trash', count: 1)
  end
```

**Comment by magdalena19** [comment]
und beim updaten der contact infos geht auch einiges schief, z.B. beim Update der Homepage gerade:

> PG::NotNullViolation: FEHLER: NULL-Wert in Spalte „latitude“ verletzt Not-Null-Constraint DETAIL: Fehlgeschlagene Zeile enthält (1, null, null, 2016-09-06 15:13:01.89677, 2016-09-06 15:13:19.076038, test, 10365, Magdalenenstr, 30, Berlin, t, 5, 01779300158, jo5cha@web.de, www.test.de). : UPDATE "places" SET "latitude" = $1, "longitude" = $2, "homepage" = $3, "updated_at" = $4 WHERE "places"."id" = $5

**Comment by andneuma** [comment]
damn... wie kann das sein?

**Comment by andneuma** [comment]
POIs werden garnicht doppelt angelegt sondern nur doppelt angezeigt...

**Comment by andneuma** [comment]
Ich schreib dafür nochmal die feature tests

**Comment by magdalena19** [comment]
> Wenn du die places_from_session(...) bspw aus der String-concat rausnimmst gibts im index keine Doppelung mehr

nur zum Verständnis: Das ist kein String-Concat, sondern ein Array-Concat

**Comment by magdalena19** [comment]
ich mache es nun einfach mit .uniq...
