### ISSUE TITLE
Rework Buttons

### ISSUE THREAD

**Issue by magdalena19** [magdalena19/lberg-map#176]
- Back (to map) Buttons
- Add via click on map
  - Add **cancel Button** 
  - Das layout ist confusing... Wenn ich die Frage "Correct location?" mit nein beantworte komme ich zu  manuellen Eingabe. Würde ich ändern: Keine Frage stellen sondern
  - Übernehmen-Button
  - Evtl. Cancel-Button (=> root_url)
  - Manuelle Eingabe-Button

**Comment by andneuma** [comment]
Keine zurück zur Karte Buttons, stattdessen Weltkugel neben Überschrift
