### ISSUE TITLE
Layout-Optimierung

### ISSUE THREAD

**Issue by kjoscha** [magdalena19/lberg-map#188]
v.a.
- Translate-Fields
- DataTables (v.a. mobil)

**Comment by andneuma** [comment]
Von meiner Seite aus folgendes:

* on-hover-caption für session-points under review
* Reihenfolge der Knöpfe in der Navbar: Suche, (Review), Einstellungen, Logout
* Ich würde die Unterschriften unter Review und Search-Knopf wegmachen, das sieht nicht gut aus und ist auch ein bisschen inkonsequent. Brauch es denn überhaupt einen Search-Button in der Navbar? Kann man nicht eigentlich alles bis auf Settings und Logout als Overlay in die Map holen? Review-Button dann einfach über die Lupe zB

**Comment by magdalena19** [comment]
> Ich würde die Unterschriften unter Review und Search-Knopf wegmachen, das sieht nicht gut aus und ist auch ein bisschen inkonsequent.

mir gefällt es, aber ich mach es weg - Das Review-Symbol ist halt nicht sehr eindeutig, aber das passt schon...

> Brauch es denn überhaupt einen Search-Button in der Navbar? Kann man nicht eigentlich alles bis auf Settings und Logout als Overlay in die Map holen?

Nee, weil man dann auf die Liste (Suche) nur über die Map gelangt. Würde es dann tatsächlich eher von der Map verschwinden lassen, was dann aber wiederum in der Mobil-Ansicht schlecht wäre. Würde es erstmal bei der Redundanz belassen...

> Review-Button dann einfach über die Lupe zB

verstehe ich ich

**Comment by andneuma** [comment]
`verstehe ich ich`

Extra Knopf für review als Overlay und den überhab der Lupe platzieren

**Comment by magdalena19** [comment]
achsoo, hab's falsch gelesen...
