### ISSUE TITLE
Einige descriptions werden nicht angezeigt

### ISSUE THREAD

**Issue by magdalena19** [magdalena19/lberg-map#199]
Von den geseedeten POI's werden einige Descriptions nicht angezeigt (weder in Liste noch auf Karte), obwohl Description vorhanden ist, wie man im entsprechenden Edit-View sieht

**Comment by magdalena19** [comment]
Hängt vermutlich damit zusammen, dass beim Seeding das reviewed-Tag der Translations random auf true oder false gesetzt wird. Wieso wird es bei false dann aber nicht im Review-View angezeigt?

**Comment by magdalena19** [comment]
@andneuma kannst du dir das annehmen? Ich repariere dann dieses POI-Zoom-Feature

**Comment by andneuma** [comment]
Is gefixt oder?

**Comment by andneuma** [comment]
Is nich so richtig gefixt, siehe production system

**Comment by magdalena19** [comment]
kann ich nicht nachvollziehen. Vielleicht mit den Seeds zu tun?
