### ISSUE TITLE
Dev Environment: Create some lorem ipsum seed POIs

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#22]
Fänds gut sowas noch einzubauen (5 POIs über bbox Berlin), sonst muss man immer soviel von Hand neu eingeben, wenn mal die DB gelöscht wurde .

**Comment by kjoscha** [comment]
lustig, da war ich gestern noch dran, weil ich den gleichen Gedanken hatte - hab's aber nicht mehr fertig bekommen...

**Comment by andneuma** [comment]
Ok, dann sitzt du da dran und ich muss mich nicht drum kümmern? Falls ja: Super!
