### ISSUE TITLE
POI description text fields cannot be edited in mobile version

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#222]
tested with android firefox

_desktop version works!_

**Comment by magdalena19** [comment]
scheint ein Problem mit wysihtml5 zu sein (das liegt unserem editor bootsy zugrunde). mit opera mobile funktioniert es und ich habe eine paar posts mt dem fehler gefunden. hm, vor allem immer schwierig zu testen :/

**Comment by magdalena19** [comment]
werde morgen probieren, direkt die neueste version von wysihtml5 zu nutzen statt bootsy

**Comment by andneuma** [comment]
kewl

**Comment by magdalena19** [comment]
@pr0totyp please deploy https://github.com/magdalena19/lberg-map/tree/wysiwig as a test. I think there is no other way do test mobile functionality here
