### ISSUE TITLE
No Plain-text descriptions

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#23]
Descriptions werden momentan als plain text gespeichert. Damit kommen wir bei der Anzeige im Modal nicht weit.
@kjoscha Wie umständlich ist es, descriptions (zB als Markdown) mithilfe eines kleinen Editors zu  verfassen, zu speichern und dann entsprechend anzeigen zu lassen?

**Comment by kjoscha** [comment]
denke ziemlich leicht: http://www.nicedit.com/
