### ISSUE TITLE
Rework slidepanel for new non-reviewed POIs

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#233]
Wenn ein neuer Punkt erstellt wird ist folgendes komisch...

a) Im Slidepanel steht für deutsche Übersetzung "wurde editiert...", sollte umbenannt werden in "warte auf Prüfung..." oder so ähnlich
b) Der "Click to edit"-Button sollte nicht angezeigt oder ausgegraut werden, weil man eh nicht editieren kann. Das gleiche gilt auch für den auto-translated-Button
c) Es sollte statt garkeiner description (weil under review?) wenigstens sowas wie "Neue Beschreibung wird geprüft" oder so ähnlich

**Comment by magdalena19** [comment]
> c) Es sollte statt garkeiner description (weil under review?) wenigstens sowas wie "Neue Beschreibung wird geprüft" oder so ähnlich

wieso gibt es dann garkeine? Es sollte doch eigentlich immer eine Description da sein, zumindest auto-translated. Oder?

**Comment by andneuma** [comment]
Naja, nicht wenn die under review sind...
