### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#24]
Erst jetzt bemerkt: Irgendwas klappt in Hinblick auf die Lokalisierung im `places` controller für die Sprachen `:fr` und `:ar` nicht. Wenn man im Formular was einträgt hat `params` die Eingabe (mit debugger gecheckt), `@place` im Anschluss allerdings nicht. Für `:de` funktionierts...

**Comment by magdalena19** [comment]
done
