### ISSUE TITLE
Absoluter speed-Abfuck wenn viele Punkte in der DB

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#244]
Hab probeweise mal 1200 Punkte geseeded und die Seite kollabiert nach jedem neuen index-request...

**Comment by andneuma** [comment]
Mmmhh... hab nochmal geguckt
* mit unseren 35 punkten real world punkten delivered das ding 1.7 MB
* bei mir lokal mit 300 punkten 2.9 MB

datatables fressen 1/2 MB, der editor ebenfalls, danach kommt unser application js code. ist schon ne menge holz, insbesondere für mobil... lohnt sich da nochmal tiefer einzusteigen

**Comment by andneuma** [comment]
Ich brauch leider auch nach #251 immernoch 9 Sekunden bei 1000 POIs

**Comment by andneuma** [comment]
Mmmhh... Chrome DevTools spucken jetzt 4,5 Sek aus für 1000 POIs, auf jeden Fall besser. Kritisch ist jetzt eher das Tiles vom ESRI-Server holen. Wie war das bei dir eigentlich?

**Comment by kjoscha** [comment]
Die tiles werden ja nachgeladen

**Comment by kjoscha** [comment]
Also die pois sind jetzt kein Problem mehr,  assets gehe ich morgen an

**Comment by magdalena19** [comment]
also irgendwie ist der master jetzt wieder voll slow. ich check mal weiter...

**Comment by magdalena19** [comment]
hui, der Places-Tabellenview ist ja viel schlimmer

**Comment by magdalena19** [comment]
yeah, also das Laden der Map ist jetzt auch mit 1000 Punkten recht flott. Bem DataTable müssen wir uns irgendwas ausgefuchstes überlegen. Man muss da denke ich auch gewissen Kompromisse eingehen...

**Comment by andneuma** [comment]
solved with last merge
