### ISSUE TITLE
Errors in der Testsuite

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#259]
@kjoscha ich hab haufenweise Poltergeist errors...

`Capybara::Poltergeist::MouseEventFailed: Firing a click at co-ordinates [0, 20] failed. Poltergeist detected another element with CSS selector 'html body nav.navbar.navbar-fixed-top' at this position. It may be overlapping the element you are trying to interact with. If you don't care about overlapping elements, try using node.trigger('click')`

Kannst du damit was anfangen?

**Comment by magdalena19** [comment]
Ja, gibt es manchmal durch Änderungen im JavaScript. Klappt meistens wie dort vorgeschlagen mit
`find('.tag').trigger('click')` statt `click('button')`

**Comment by andneuma** [comment]
Warum packt Travis das?

**Comment by andneuma** [comment]
Außerdem seit dem Speed improv merge error messages in feature tests, (zB Review place Feature Test):

```
Error: Map container is already initialized.
Error: Invalid GeoJSON object.
```
