### ISSUE TITLE
Add from current location

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#26]
Das wäre mE die sinnvollste Nutzung des reverse-geocodings (wahrscheinlich wird niemand über ein Zielkreuz nen Punkt eintragen), sollten wir - wie bei der anderen Karte auch - einbauen.

**Comment by kjoscha** [comment]
doch,  so einen Spiel- oder Fußballplatz könnte ich mir schon vorstellen über einen Klick einzutragen. aber ja,  Funktion sollte wieder rein...
