### ISSUE TITLE
Authentifizierung bzw. "Who can contribute (how)?"

### ISSUE THREAD

**Issue by magdalena19** [magdalena19/lberg-map#30]
Wir brauchen hier ein Konzept. Ich bin immer noch dafür, dass man sich nicht registrieren muss, um einen Punkt hinzuzufügen und stattdessen ein solides Anti-Spam-Konzept umgesetzt wird.

Schritt 1 ist ein Captcha.
Ein super einfach zu integrierendes Captcha für den Anfang ist das hier (gerade in 2 Minuten testweise eingebaut):  https://github.com/pludoni/simple-captcha

**Comment by magdalena19** [comment]
Als weiterer Spam-Schutz kann ein Honigtopf (versteckter Captcha, den nur Bots ausfüllen) eingebaut werden: https://github.com/curtis/honeypot-captcha

**Comment by andneuma** [comment]
Jo, ich würd heut autotranslation fertig machen und mir das mal anschauen

**Comment by andneuma** [comment]
Also mein Vorschlag wäre folgender, können wir ja bei der nächsten Gelegenheit diskutieren:

* Spamschutz auf jeden Fall
* Neu hinzugefügte Punkte sind erstmal nur als *Preview* verfügbar, solang der session cookie gilt
* Die Punkte werden dann von einer Editor_innen-Gruppe peer-reviewed und freigeschaltet
* Wir setzen ein total basales User-Management auf, wo es entweder garkeine (alle sind Editor_innen, Admin-Tasks laufen über die Konsole aufm Server) oder halt nur zwei Rollen (Admins und Editor_innen) gibt.
