### ISSUE TITLE
Editor funktioniert nicht

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#31]
Jo,

Editor funktioniert nicht, konkret (was ich probiert hab):

* Keine Zeilenumbrüche
* Listen gehen nicht

Text styling funktioniert aber

**Comment by magdalena19** [comment]
Liegt vermutlich daran, dass der Sanitizer zu streng eingestellt ist. Ich habe ihn so konfiguriert, dass alle HTML-Tags, die erlaubt sind, explizit angegeben werden. Werde es mal abgleichen...

**Comment by magdalena19** [comment]
https://github.com/magdalena19/lberg-map/commit/fcea4474ac9d32058630cd54739e2c7d5bb19705
