### ISSUE TITLE
add Travis continous integration

### ISSUE THREAD

**Issue by Powerglove** [magdalena19/lberg-map#37]
https://docs.travis-ci.com/user/languages/ruby

don't forget the status image on the readme:
https://docs.travis-ci.com/user/status-images/

**Comment by magdalena19** [comment]
not working yet. postgres connection needs to be configured in the .travis.yml file

**Comment by magdalena19** [comment]
jo läuft nun. Auf den Button im Readme klicken um Fehler u.a. zu sehen.

**Comment by andneuma** [comment]
hast dus mal mit nem faulty merge probiert?

**Comment by magdalena19** [comment]
was probiert mit welchem Merge?

**Comment by andneuma** [comment]
ob travis meckert, wenn du einen branch in master mergen willst, wo
nicht alle tests passen (das war doch der sinn oder?)

**Comment by magdalena19** [comment]
achso, gerade ist der Button noch nicht zu sehen bei den Pull Requests. Kann sein, dass erst neue PR's beachtet werden.

**Comment by magdalena19** [comment]
jo klappt: https://github.com/magdalena19/lberg-map/pull/61
