### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#4]
#### What to test
*I'd test everything using Minitest, Capybara using Guard*

- [x] Controller tests
- [x] Module tests
- [ ] Basic E2E tests

#### Minitest reporter configuration

Nice article: http://chriskottom.com/blog/2014/06/dress-up-your-minitest-output/

**Comment by magdalena19** [comment]
Verstehe die Kategroein nicht. Was siond Module tests? Und welcher Kategorie gehören die Klicktests an? Ich kenne das als 'Feature tests'...

**Comment by andneuma** [comment]
Viele Tests sind rot

**Comment by andneuma** [comment]
> Klicktests

Unformalisierte Tests durch manuelles, wildes Herum-Geklicke im Browser ;)
