### ISSUE TITLE
open translations

### ISSUE THREAD

**Issue by magdalena19** [magdalena19/lberg-map#43]
flash messages

**Comment by andneuma** [comment]
Können wir uns als Konvention darauf einigen keine "falschen" (-> urspr. dt. Übersetzungen copy n paste in die ar und fr locale) und statt dessen leere Übersetzungen in den locale-files stehen zu haben? Machts uns auch einfacher später, denn wir matchen in den locale-files die Übersetzungs-Leerstellen im Interface einfach via `: ''`, extrahieren die Zeilen und geben das raw Leuten zum übersetzen...

**Comment by magdalena19** [comment]
jo stimmt

**Comment by andneuma** [comment]
Es wäre cool, wenn wir das Interface tatsächlich langsam mal in einen fertigen Stand bringen, weniger was das Design sondern mehr was so "auftauchende Wörter" angeht. Dann würde ich demnächst Leute für folgende Übersetzungen anhauen:

* English
* French
* Arabisch
* Farsi
* Spanisch + Catalan
* Portugiesisch
* Japanisch (kenn ich zumindest jmd, die das sofort übersetzen würde, auch wenn wirs jetzt vielleicht nicht brauchen)

Für _slawische Sprachen_ kenne ich niemanden, bekommen wir aber irgendwie hin. Wir sollten die Liste auf jeden noch erweitern um das, was Leute die wir kennen noch so können, sodass zumindest die 'generic version' in so vielen Sprachen wie möglich vorhanden ist. Dafür aber wie gesagt muss das Interface erstmal in einem fertigen Zustand sein

**Comment by andneuma** [comment]
Offene Interface-Translations

* `'supply valid postal code (5 digits)'` in `validation` of `place-model`
