### ISSUE TITLE
Neuer Punkt: Beschreibung in mehr als einer Sprache

### ISSUE THREAD

**Issue by magdalena19** [magdalena19/lberg-map#44]
Wenn ich beim Ort-Erstellen die Beschreibung direkt in mehr als einer Sprache angebe, wird trotzdem nur eine gespeichert (in meinem Fall arabisch) und die anderen automatisch übersetzt (und damit überschrieben).

**Comment by andneuma** [comment]
Problem tritt bei mir im Branch `locate-me` nicht auf

**Comment by magdalena19** [comment]
bei mir schon. und nu?

**Comment by andneuma** [comment]
weird (weil ich das problem nicht habe), du hast denke ich recht, liegt an dieser zeile:

`languages_of_empty_descriptions = available_locales - [native_translation.locale]`

Das Ding braucht eh nochmal refactoring, würde das issue entsprechend offenlassen und mit [#36](https://github.com/magdalena19/lberg-map/issues/36) zusammen lösen
