### ISSUE TITLE
captcha partial not HAML

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#45]
...sondern erb + css im selben file definiert

**Comment by magdalena19** [comment]
O_o

**Comment by magdalena19** [comment]
achso, das war vorgegeben. Umbauen oder lieber mit Kommenatr darauf verweisen, dass es aus deren Repo übernommen wurde?

**Comment by andneuma** [comment]
Mmmhhh... ich fänd Konsistenz schöner muss ich sagen und wäre für umbauen. Ist ja nicht weiter dramatisch...

**Comment by andneuma** [comment]
Meinetwegen dann mit Kommentar darauf verweisen, dass man das original umgebaut hat ;)

**Comment by magdalena19** [comment]
Oki

**Comment by andneuma** [comment]
Machst du dit?

**Comment by kjoscha** [comment]
jo klar

**Comment by andneuma** [comment]
Obwohl, vielleicht mach ich das auch einfach zur HAML-Übung

**Comment by magdalena19** [comment]
jo mach das ruhig, aber sag Bescheid, wenn du damit beginnst, sonst würde ich es nämlich bald tun (Würde dann im gleichen Atemzug das Sytling anpassen)

**Comment by magdalena19** [comment]
siehe neuer PR
