### ISSUE TITLE
Categories <-> Tags

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#5]
Wollen wir `categories` vielleicht anders realisieren als über ein attribute in `places`? Gibt zB Gems dafür oder man baut das selbst...

Railscast zum Thema: http://railscasts.com/episodes/382-tagging

**Comment by kjoscha** [comment]
ja, macht auf jeden Fall Sinn!

**Comment by magdalena19** [comment]
bzgl. autocompletion: das hier ist leicht zu implementieren: https://jqueryui.com/autocomplete/#multiple

**Comment by magdalena19** [comment]
@andneuma  du fragtest irgendwo nach der Übersetzung der Tags (deshalb sowas nicht in Slack, grrr). Ich habe mir gerade auf dem Rad etwas Gedanken dazu gemacht:
Mit dem tollen Globalize, das ja nun implementiert ist, sollte für die Tags ganz leicht ein translation table angelegt werden können. Es muss halt irgendwie sichergestellt werden, dass bei Hinzukommen eines Tags auch die Übersetzungen angelegt werden. Wir könnten zwar auch z.B. Englisch als Fallback-Language setzen, aber das wird auf jeden  Fall irgendwann zu einem wilden Misch aus übersetzten und nicht-übersetzten Tags führen.
So oder so ist ja die Hautpfrage, ob wir ein dynamisches oder festgelegtes Tag-Set anbieten wollen. Ich bin aus den gleichen Gründen wie damals bei der PHP-Version für zweiteres. Dann hat sich auch dieses Problem hier weitgehend gelöst, weil wir nur einen einmalige Übersetzung brauchen. Später dynamisch machen können wir es immer noch.
Was meinst du?

**Comment by andneuma** [comment]
> So oder so ist ja die Hautpfrage, ob wir ein dynamisches oder festgelegtes Tag-Set anbieten wollen

Finde ich gut, let's keep it easy. Man könnte dazu einen kleinen Button mit neue Kategorie vorschlagen?

**Comment by kjoscha** [comment]
>Man könnte dazu einen kleinen Button mit neue Kategorie vorschlagen dazupacken

ja finde ich gut

**Comment by magdalena19** [comment]
schließe es erstmal. Tags werden übersetzt und können per Checkbox ausgewählt werden
