### ISSUE TITLE
Geocoder features: Filter Points > n km

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#51]
...

**Comment by magdalena19** [comment]
kannst du das kurz erläutern? Du meinst damit nur Punkte anzeigen, die unter einer bestimmten Entfernung zum User liegen?

**Comment by andneuma** [comment]
genau

**Comment by magdalena19** [comment]
ALso ein Button nach dessen Klick dann der Geolocation-Service angeworfen wird?

**Comment by andneuma** [comment]
genau, oder ein eingabefeld oder ein slider, womit man die entfernung
(in sinnvollen km-abständen) justieren kann

**Comment by magdalena19** [comment]
okay. das klingt spaßig. Übernehme ich...
