### ISSUE TITLE
Interface design: Button Bar

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#52]
So eine Buttonleiste hätte ich gern für die Kartenansicht: https://www.openstreetmap.org/

**Comment by magdalena19** [comment]
du meinst die bisherigen Buttons in so einem Style? 

Am 14. Juni 2016 14:44:11 MESZ, schrieb Andreas Neumann <notifications@github.com>:
>So eine Buttonleiste hätte ich gern für die Kartenansicht:
>https://www.openstreetmap.org/
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/magdalena19/lberg-map/issues/52

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by andneuma** [comment]
genau!

**Comment by magdalena19** [comment]
schau dir die Buttons mal an in #54
