### ISSUE TITLE
Impressum / About-Page / Disclaimer

### ISSUE THREAD

**Issue by magdalena19** [magdalena19/lberg-map#55]
to be written...

**Comment by andneuma** [comment]
Impressum könnte man evtl. über aiL machen, würde ich ma nachfragen. Disclaimer sollte man Suse mal fragen, die kennt sich mit Haftungsausschluss-Fragen aus

**Comment by magdalena19** [comment]
geht das nun klar mit AiL?

**Comment by andneuma** [comment]
noch unklar, du kannst mal bei uns aufm board fragen

**Comment by andneuma** [comment]
Hab aufm Board angefragt
