### ISSUE TITLE
Internationalisierung

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#6]
@kjoscha: Ist das Thema von Mehrsprachigkeit nicht auch durch die Rails-eigene I18n-API realisierbar? Kannst du das deinen Guru auf Arbeit vielleicht mal fragen? Ich könnte das Thema sonst auch mal zum nächsten Co-Learners Meetup mitnehmen und da mal nachhaken.

**Comment by kjoscha** [comment]
jo, ich schau es mir mal an und frage Til ggf. Aber wird bestimmt Sinn machen...

**Comment by kjoscha** [comment]
Das ist ja auch scheinbar recht easy zu benutzen. Wie wir dynamische Übersetzungen (statt hardgecodeter Speicherung in "locale"-Files) nutzen können, wird hier beantwortet: http://stackoverflow.com/questions/1346939/rails-store-translations-in-database

**Comment by kjoscha** [comment]
ups, das ist sehr alt. Globalize3 könnte helfen:
> ...and while it works well for static text it won’t help us display text from the database in different languages. To do this we need to store each translation in a database table and the Globalize3 gem makes doing this much easier. Globalize3 creates a separate table to store translations for each model that we use...

http://railscasts.com/episodes/338-globalize3?view=asciicast
