### ISSUE TITLE
ActiveRecord and parallel editing?

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#64]
Any idea whether this might be an issue, e.g. parallel editing in 'preview mode' as 'guest user' and editing in 'authorized mode' as 'registered user'?

**Comment by kjoscha** [comment]
i do not understand this scenario...

**Comment by andneuma** [comment]
(non registered) translator: Translates english description of POI A
(registered) reviewer: Edits other parts of POI A
translator saves first. What happens to reviewers edits?

**Comment by magdalena19** [comment]
In diesem Szenario würde die zweite Speicherung halt die erste überschreiben, oder?

Was ich gut fände und was einen vertretbaren Aufwand mit sich brächte, wäre, wenn beim speichern darauf geprüft wird, ob seit dem Laden des Punktes der Punkt nochmal geändert wurde (über den updatet_at-Timestamp - Vorsicht: Wird glaub ich nicht automatisch aktualisiert. Da muss man selbst für sorgen) und wenn das der Fall ist, eine Meldung im Sinne von "Jemand anderes hat den Punkt editiert. Sichere deine Änderungen und aktualisiere die Ansicht um Änderungen zu sehen..."

Hoffe damit habe ich dein Szenario richtig verstanden.

**Comment by andneuma** [comment]
jup, hast du ;) Ich recherchier das nochmal und kümmer mich drum

**Comment by magdalena19** [comment]
ist ja redundant wegen #95
