### ISSUE TITLE
Zoom level on locale change

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#69]
Zoom level springt (unter Firefox) zurück auf Ausgangswert wenn man die locale switched

**Comment by kjoscha** [comment]
da springt alles zurück.  ist mit normaler REST-Logik nicht einfach zu umgehen...

**Comment by magdalena19** [comment]
Bei der PHP-Version hatte ich ja alles mit AJAX (also mit asynchronen Requests) gemacht, das geht hier nicht, weil die Logik, mit der in unserer App Content übersetzt wird, völlig anders funktioniert. Es wird ja quasi die gesamte App neu geladen. Bei der PHP-Version wurden hingegen einfach alle getaggten Content-Elemente per Javascript überschrieben....

**Comment by magdalena19** [comment]
Was gehen würde: Mit einem Cookie den Karten-Zustand speichern und dann wieder abrufen. Ist es aber nicht wert, oder? Ich denke im normalen Use Case wird ja nur einmal die Sprache ausgewählt (was dann aber in der Tat gespeichert werden könnte)

**Comment by andneuma** [comment]
Genau, wenns kompliziert ist passt das schon. VA die test-user werden das wahrscheinlich bemerken, wenn sie rumswitchen und gucken was passiert.

**Comment by andneuma** [comment]
>     Marker sind auf jeden Fall cool. Wie einfach ist es, da unterschiedliche Farben für die verschiedenen Kategorien einzubauen?
>
