### ISSUE TITLE
'Try translation'-Button?

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#7]
Für nicht vorhandene Übersetzungen nach Sprache xyz könnten wir versuchen mittels API xyz (google translate, besser vielleicht aber was anderes) nen translate-Button anzubieten. Da kommt dann meist nichts 100% gutes bei raus, aber zumindest hat man vielleicht erstmal ne grobe Idee um was es sich handelt (sollte man auch drauf hinweisen...)

API comparison: https://www.neno-translate.com/en/blog/48-best-machine-translation-api

**Comment by kjoscha** [comment]
find ich ne super Idee! Vielleicht sogar so, dass alle Texte automatisch per Google-Translate übersetzt werden und dann mit deutlichem Hinweis darauf, dass es sich um eine maschinelle Übersetzung handelt und z.B. in kursiver oder ausgegrauter Schrift angezeigt wird + Direktlink zum Übersetzungsformular.

**Comment by andneuma** [comment]
> Vielleicht sogar so, dass alle Texte automatisch per Google-Translate übersetzt werden und dann mit deutlichem Hinweis darauf, dass es sich um eine maschinelle Übersetzung handelt und z.B. in kursiver oder ausgegrauter Schrift angezeigt wird + Direktlink zum Übersetzungsformular.

ja, top!

**Comment by andneuma** [comment]
> Vielleicht sogar so, dass alle Texte automatisch per Google-Translate übersetzt werden und dann mit deutlichem Hinweis darauf, dass es sich um eine maschinelle Übersetzung handelt und z.B. in kursiver oder ausgegrauter Schrift angezeigt wird + Direktlink zum Übersetzungsformular.

Ich glaube wir müssen das sogar so machen. Für die Nutzung der Translation APIs braucht man Keys. Die beste kostenlose API kommt von Bing, den Key holt man sich wie folgt: http://www.restlessprogrammer.com/2013/03/setting-up-free-bing-translator-api.html

Ekligt, aber naja, muss man dann wohl durch. Damit hat man dann 2 mio Characters / Monat. Kurze Hochrechnungen:

* Eine Beschreibung mit 400 Chars
  * Übersetzt nach Farsi, Arabisch, Englisch, Deutsch, Russisch
  * Macht 5000 Chars
  * Davon könnte man dann pro Monat 400 übersetzen

* Eine Beschreibung mit 250 Chars
  * Übersetzt nach Farsi, Arabisch, Englisch, Deutsch, Russisch
  * Macht 1250 Chars
  * Davon könnte man 1600 pro Monat übersetzen

Live-Übersetzung pro Client via Knopf läuft also nicht, übersetzen bei Erstellung des POI ist besser. Außerdem ist das für ne bundesweite app mit übelst vielen POIs (wäre der Traum) auch ein zweifelhafter Ansatz.
Außerdem müssen wir die übersetzen Chars in der App tracken, sonst bekommen wir Probleme.

Das passende Gem für die Translations gibts hier: https://github.com/relrod/bing_translator-gem
