### ISSUE TITLE
Map extremely slow after inserting ~2000 points...

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#72]
Wie der Titel schon sagt.

@kjoscha kannst ja #71 mal pullen, 2000 points seeden und dann gucken. Bei mir ist es WEIT ab von flüssig :/

**Comment by magdalena19** [comment]
jo, war zu erwarten.
Kurze Erklärung meiner (recht sicheren) Hypothese dazu:

Es werden momentan alle POIs zu einem GeoJson serialisiert, welches ALLE Informationen, also z.B. auch Descriptions auf allen Sprachen enthalten. Kannst ja mal in deinem Browser-Debug-Tool schauen, wie groß die Datei ist. Ich denke, sie ist ziemlich riesig für Browser-Processing-Verhältnisse.

Lösungsansätze liegen aber natürlich parat. Punkte werden nur mit Name, ID und Koordinaten serialisiert und nach Bedarf werden Informationen aus der DB nachgeladen. Da haben wir wieder ein klassiches Szenario für das so wichtige AJAX :)

Baue ich als nächstes ein...

**Comment by andneuma** [comment]
jut

**Comment by magdalena19** [comment]
gerade nochmal Gedanken drüber gemacht:

Es gibt ja dieses [Leaflet-Cluster-Plugin](https://github.com/Leaflet/Leaflet.markercluster), welches sehr, sehr performant arbeitet. Damit haben wir es ja bei [RubyCars](http://rubycars.org/) auch möglich gemacht. Das baue ich erstmal ein und schaue dann, bei wie vielen Punkten dann der gefühlte Performance-Grenzwert liegt. Davon ausgehend schaue ich dann, wie ich mit der erwähnten AJAX-Umstellung vorgehe...

**Comment by magdalena19** [comment]
Nochmal ein Gedanke dazu: Du hattest ja mal so etwas im Kopf, wie Punkte filtern nach Entfernung. Das ist zwar etwas blöd, weil der Location-Service ja nicht immer gut funktioniert u.a., aber wäre es nicht sinnvollm Punkte einfach nach Entfernung zum aktuellen Viewport zu filtern?! Also wenn mein Karten ausschnitt Berlin zeigt und ich auf die POI-Übersicht klicke, dann werden nur Punkte in Berlin und Umgebung angezeigt...

**Comment by magdalena19** [comment]
hm...doch alles ganz schön kompliziert wenn man es versucht zu ende zu denken. wir wollen erstmal sowieso in berlin bleiben, oder?

**Comment by andneuma** [comment]
mmhh... gute frage. ich würde sagen ja, aber es macht mE natürlich sinn,
das gleich großskaliger zu denken, wenn wir es generisch halten wollen.

**Comment by magdalena19** [comment]
ok, hab mir das jetzt alles mal genauer angeschaut. Wird doch ein komplexer Umbau auf Dauer. Eigentlich gibt es zwei Performance-Probleme bei dehr vielen Punkten:

**1. Schlechte Map-Interaction-Performance**

- Lässt sich nur durch Reduzierung der Punkte und durchs Clustern lösen.

- Cluster baue ich gerade ein.

- Wenn sich eine Erwwiterung auf andere Städte abzeichnen sollte, müssen wir wohl eine Stadtauswahl an den Anfang setzen. Könnte z.B. ein Fenster sein, das noch vor der Kartenansicht beim Aufruf der Seite erscheint

**3. Lange Ladezeite der Seite**

- Da gibt es potenziell viele Baustellen. Tatsächlich macht momentan das Abfragen der Kategorie-ID's für jeden Punkt einen Großteil aus (weil das über die Referenztabelle läuft).
Daher werde doch wieder den AJAX-Kategoriefilter, den ich schonmal drin hatte, einbauen.

Zum anderen werden momentan alle POI's zweimal serialisiert - einmal für die Punkte und einmal für die Liste, das muss natürlich geändert werden. Daran mache ich mich dann als nächstes.


@andneuma wie du siehst, ist doch viel zu tun hinsichtlich Performance. Bin damit also erstmal eine Weile beschäftigt, so dass du alle anderen offenen Punkte übernehmen kannst ;)

**Comment by andneuma** [comment]
allright. wie hast du die performance-sachen eigentlich
getestet/gebenchmarkt?

**Comment by kjoscha** [comment]
>allright. wie hast du die performance-sachen eigentlich getestet/gebenchmarkt?

Ladezeiten über die Zeitangabe im Terminal, z.B:

> Completed 200 OK in 315ms (Views: 255.0ms | ActiveRecord: 0.2ms)

und Ladezeiten von Javascript, Json und co. über Firebug...
