### ISSUE TITLE
Layout / Design

### ISSUE THREAD

**Issue by magdalena19** [magdalena19/lberg-map#73]
von @andneuma:

Jo, cool, dass endlich mal ein bisschen mehr Style reinkommt. Einige Anmerkungen zum Design:

- [x] Farbverlauf aus der Navbar würde ich rausnehmen, auf jeden Fall nicht grün nach schwarz machen

- [x] User-Zeugs (auch wenn nur zwei Items) können meinem Empfinden nach in ein dropdown

- [x] Ich würde die Links ausschreiben statt icons zu verwenden, denn kleine devices bekommen ja das dropdown (falls das der Hintergrund ist). Ausgeschriebens ist würde ich sagen immer eindeutiger.

- [ ] Marker sind auf jeden Fall cool. Wie einfach ist es, da unterschiedliche Farben für die verschiedenen Kategorien einzubauen?

**Comment by andneuma** [comment]
Marker in anderer Farbe (terracotta?), falls unreviewed?

**Comment by andneuma** [comment]
Im Interface: statt "All" -> "All categories", dann weiß man auch gleich was man da klickt

**Comment by magdalena19** [comment]
>Marker in anderer Farbe (terracotta?), falls unreviewed?

Das sind sie oder das sollen sie sein?

**Comment by magdalena19** [comment]
Zu Markern auch schon den neuen Cluster-Branch/PR beachten, da dort nun auch CLuster-Icons hinzu gekommen sind

**Comment by andneuma** [comment]
Wie machen wirn das nu? Machen wir unterschiedliche marker-farben für den reviewed-status? Vielleicht ist das ja auch quatsch, kA. Evtl. würde es aber den "ich trage als guest-user aktiv was zum entstehen der Karte bei"-Faktor, wenn man die Punkte zusätzlich zur POI-Liste in der sidebar noch auf der Karte - dann halt inner anderen Farbe - sieht...

**Comment by magdalena19** [comment]
jo find ich gut so...

**Comment by andneuma** [comment]
Dann Lachsfarben?
