### ISSUE TITLE
Dropdown für locales und modal "Choose your language"?

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#76]
Wollen wir sowas wieder einbauen? Fänd ich cool, weil

a) die navbar ein bisschen aufgeräumt würde (dropdown) und
b) man von vornherein durchs interface zur richtigen sprachversion geleitet wird ohne sich orientieren zu müssen (modal wie in der alten version glaube ich)

**Comment by magdalena19** [comment]
jo find ich gut

**Comment by andneuma** [comment]
Hier gibts issues zwischen bootstrap und der app. wenn ich versuche mit bootstrap-eigenen klassen ein dropdown-menu einzubauen (siehe #80) das hinzubekommen passiert nix. ist irgendwie ein js-problem. hintergrund ist möglicherweise, dass durch mehrfaches laden von js-files da genau zweimal der dropdown-link getoggelt wird, hab aber eben nicht so richtig einen plan davon. vielleicht siehst du es ja sofort auf anhieb, falls nicht ist es gerade nicht so krass wichtig.

**Comment by magdalena19** [comment]
ja, kenne das Problem. Kann das übernehmen
