### ISSUE TITLE
Back button still not working?

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#78]
`action_name == 'edit' ? places_path : root_path` ist noch ein bisschen hacky. Eigentlich wärs ja total cool einfach zur zuletzt besuchten Seite zurückzukehren und nicht hardgecodete Optionen zu haben, oder?

**Comment by magdalena19** [comment]
nee, ich glaub da gab es bestimmte Fälle, auf denen das nicht sinnvoll ist. Ist aber vielleicht nicht mehr so. Werde ich mir anschauen
