### ISSUE TITLE
Crowdsourcing-Übersetzungsfunktion

### ISSUE THREAD

**Issue by magdalena19** [magdalena19/lberg-map#84]
Das ist mit das Wichtigste, das bisher fehlt: Die Crowdsourcing-Übersetzungs-Funktion

**Comment by andneuma** [comment]
Stimmt. Ist die Frage, wie wirs machen wollen. Ganz, ganz einfach: So wie beim reviewen ne extra 'contribute_translation' methode (working title) + view wo man nur sprache verändern kann erstellen, submit updated dann den Record.

**Comment by andneuma** [comment]
Discussion via PR #88
