### ISSUE TITLE
Group by geo-features 

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#93]
Wäre cool wenn man die Anzeige der POI-Listen verbessern könnte. Eine lange Liste ist für User_innen, die spezifisch etwas suchen erstmal nicht so cool. Besser - auch fürs reviewen - wäre eine Unterteilung der Liste zB nach Bezirken oder den Categories. Was meinst du?

**Comment by magdalena19** [comment]
ja, finde ich auch. Wir sollten den Place-Index-View weiter ausbauen und die slidepanel-Liste auf der Map entfernen.

**Comment by andneuma** [comment]
Man kann die datatables auch prima gruppieren und die gruppenelemente ausfahren lassen, sehr schick

**Comment by magdalena19** [comment]
ok. auch aufgrund dieser schrecklichen Redundanz beim Laden der POI-Inhalte in map.js würde ich gerne das places-list-slidepanel herausnehmen. Wir sollten dann aber die Listen-Ansicht (search places) irgendwo prominenter anbieten, oder?
