### ISSUE TITLE
Captcha funktioniert nicht auf Production

### ISSUE THREAD

**Issue by magdalena19** [magdalena19/lberg-map#96]

**Comment by magdalena19** [comment]
gerade gesehen, dass es garnix mit Android zu tun hat, sondern allgemein mit der Production-Umgebung. Ich denke, dass es irgendwie mit Imagemagick zu tun hat, welches eine Abhängigkeit von simple_captcha ist. Ist aber eigentlich auf Uberspace vorinstalliert. ich würde sagen, wir lassen es erstmal in Ruhe und hoffen, dass es auf dem neuen Server laufen wird.  @pr0totyp also an ImageMagick-Installation denken ;)

**Comment by andneuma** [comment]
Hat sich da getan?

**Comment by magdalena19** [comment]
denke ja. Betrifft zumindest nur Uberspace
