### ISSUE TITLE
Templates for ' xxx not found'?

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#99]
Brauchen wir wenn URL nicht gefunden wird, oder?

**Comment by kjoscha** [comment]
liegen doch hier, oder? https://github.com/magdalena19/lberg-map/tree/master/public

**Comment by andneuma** [comment]
Ok, muss man die dann noch extra einbinden, weißt du das?

**Comment by kjoscha** [comment]
das wäre ja voll un-ruby-like, aber mal schauen...

**Comment by andneuma** [comment]
ah, verstehe, das ist ein unterschied zwischen production und
development. habs grad mal in der production version ausprobiert und
bekomme da ne 404-seite zurück. alles gut
